### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by ctw8989** [honwen/openwrt-shadowsocksr#1]
make[5]: Entering directory '/home/wsh/openwrt/build_dir/target-x86_64_musl/curl-7.58.0/lib'
  CC       vtls/libcurl_la-mbedtls.lo
vtls/mbedtls.c: In function 'Curl_mbedtls_sha256sum':
vtls/mbedtls.c:1032:3: error: implicit declaration of function 'mbedtls_sha256_ret'; did you mean 'mbedtls_sha256_free'? [-Werror=implicit-function-declaration]
   mbedtls_sha256_ret(input, inputlen, sha256sum, 0);
   ^~~~~~~~~~~~~~~~~~
   mbedtls_sha256_free
cc1: some warnings being treated as errors
Makefile:2153: recipe for target 'vtls/libcurl_la-mbedtls.lo' failed
make[5]: *** [vtls/libcurl_la-mbedtls.lo] Error 1
make[5]: Leaving directory '/home/wsh/openwrt/build_dir/target-x86_64_musl/curl-7.58.0/lib'
Makefile:921: recipe for target 'install-recursive' failed
make[4]: *** [install-recursive] Error 1
make[4]: Leaving directory '/home/wsh/openwrt/build_dir/target-x86_64_musl/curl-7.58.0'
Makefile:179: recipe for target '/home/wsh/openwrt/build_dir/target-x86_64_musl/curl-7.58.0/.built' failed
make[3]: *** [/home/wsh/openwrt/build_dir/target-x86_64_musl/curl-7.58.0/.built] Error 2
make[3]: Leaving directory '/home/wsh/openwrt/package/network/utils/curl'
package/Makefile:106: recipe for target 'package/network/utils/curl/compile' failed
make[2]: *** [package/network/utils/curl/compile] Error 2
make[2]: Leaving directory '/home/wsh/openwrt'
package/Makefile:102: recipe for target '/home/wsh/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/wsh/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wsh/openwrt'
/home/wsh/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by ctw8989** [comment]
是@aa65535的mbedtls的问题

**Comment by honwen** [comment]
cannot reproduce
