### ISSUE TITLE
shadowsocksR无法启动

### ISSUE THREAD

**Issue by sourdreaming** [honwen/openwrt-shadowsocksr#3]
路由器型号：WNDR3800CH
路由器固件版本：OpenWrt SNAPSHOT r7093-4fdc6ca / LuCI Master (git-18.152.60731-18b5b06)
固件内核版本：4.9.105
使用的shadowsocksR版本：17a3f97的releases中的
shadowsocksr-libev_2.5.2-d4904568c0bd7e0861c0cbfeaa43740f404db214_mips_24kc.ipk
启动延时：选择“未启用”与”5秒“均无法启动shadowsocksR
日志：
_[2018-06-02 19:02:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:03:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:04:01] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:05:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:06:00] Problem-DNS decteted, restarting shadowsocksr...
udhcpc: started, v1.28.3
udhcpc: sending discover
udhcpc: no lease, failing
[2018-06-02 19:07:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:08:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:09:00] Problem decteted, restarting shadowsocksr...
[2018-06-02 19:10:00] Problem decteted, restarting shadowsocksr..._

_/usr/bin_ 下
![image](https://user-images.githubusercontent.com/15834651/40880214-3892f640-66df-11e8-82f0-6f3edc3690f6.png)

**Comment by wgjwillis** [comment]
我的理解：
[2018-06-02 19:06:00] Problem-DNS decteted, restarting shadowsocksr...
udhcpc: started, v1.28.3
udhcpc: sending discover
udhcpc: no lease, failing
---------
上面这几句才是关键，从dnsmasq-full 的角度来考虑、排错。比如相关服务的日志权限问题、日志导致的空间问题。重启服务。等等。

不要只把注意力放到shadowsocksr服务上。
希望对你有帮助。


--

**Comment by honwen** [comment]
请先确认ssr的配置正确

**Comment by honwen** [comment]
Not Responding

**Comment by helllkz** [comment]
我也遇到这个问题
我是dnspasq -> chinadns -> dnsforwarder
dns转发到5353端口（chinadns监听）,上游再到61.139.2.69,127.0.0.1#5300（dns转发监听）
dnsforwarder试过默认的8.8.8.8，也试过到127.0.0.1:23456(SS透明代理端口) 127.0.0.1:5355（SS端口转发），都报一样的错误，国内上网没问题
那设置有2个问题了
1. dnsforwarder的上游应该是配置哪个呢，直接8.8.8.8，还是透明代理端口，或者端口转发端口呢
2. chinadns和dnsforwarder用其他人编译的应该也行吧，dnsmasq-full是用的openwrt自带的

**Comment by honwen** [comment]
@helllkz Recommend my repo: https://github.com/chenhw2/openwrt-dnsmasq-extra

**Comment by helllkz** [comment]
嗯，试试dnsmasq-extra，这个好像不带luci吧，还要去aa65535那儿下一个
另外这种方案下，是不是ssr的端口转发和sock代理都用不上呢，dnsforwarder设置成8.8.8.8就可以了，自然就能走透明代理了

**Comment by honwen** [comment]
Clearly, u dont know how my repo work and what it do.

**Comment by AHBICJ** [comment]
挖个坟吧，首先建议用/etc/init.d/shadowsocksr restart -w 看一下到底是什么出错
Error loading shared library libmbedcrypto.so.3: No such file or directory (needed by /usr/bin/ssr-redir)
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_update: symbol not found
我这边是这个，我联想到安装的时候提示以来不满足只装了编译出来的libmbedtls，没装mbedtls-util
于是scp \*mb\* root@192.168.123.1:/tmp  (复制两个编译出的包)
root@Alice:/tmp# opkg remove libmbedtls --force-depends && opkg install \*mb\*    (安装他们,我之前因为这个报错更新了libmbedtls,就先卸载)

希望能够对之后来的像我一样的小白有所帮助，真的搞了好久...

UPDATE:删除以上言论，我只是让那个自测的脚本死掉，ssr是能跑的。现在是libmbedcrypto这个找不到随他了，:-(，等过两天再折腾吧。

update: 又opkg更新了libmbedtls，没错就是被我卸载的那玩意儿（util在的，没更新），就行了，可能curl是直接装的，杂七杂八也不懂TAT..
[2020-10-17 02:11:00] shadowsocksr No Problem. 太感动了

update: libcurl 依赖的和shadowsocksr-libev依赖的libmbedtls不是一个版本，选择了ssr，后来重新编译了curl, 他有一个新的依赖libwolfssl24 总算是真的没问题了
