### ISSUE TITLE
Makefile' has a build dependency on 'libmbedtls', which does not exist

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-shadowsocksr#5]
Hey Chen
thanks for updating your repository again
when I try compile your newest one 

I found this(even I try modify libmbedltls to libmbedtls)

.........................................................................................................
WARNING: Makefile 'package/feeds/openwrt-shadowsocksr/Makefile' has a build dependency on 'libmbedtls', which does not exist
WARNING: Makefile 'package/feeds/openwrt-shadowsocksr/Makefile' has a build dependency on 'libpcre', which does not exist

is there some wrong

please help

**Comment by honwen** [comment]
Met same issues as building with OpenWRT 18.06

Please Compile it with [LEDE SDK 17.01.X](https://github.com/lede-project/source/tree/v17.01.6)

OR compile old version: https://github.com/chenhw2/openwrt-shadowsocksr/commit/78ab21a7b5f0f7dcb4a7a6d1583f2f3dc5f1f466

**Comment by jack338c** [comment]
OK, I got it
by the way ,I supose here : PKG_BUILD_DEPENDS:=libmbedltls libpcre  should be" libmbedtls" no L

**Comment by honwen** [comment]
Same issues in https://github.com/shadowsocks/openwrt-shadowsocks,

and still no better solution.

**Comment by jack338c** [comment]
ok,thanks Chen

**Comment by chuntsky** [comment]
18.06的SDK中，把makefile中的PKG_BUILD_DEPENDS:=libmbedtls libpcre，换成PKG_BUILD_DEPENDS:=mbedtls pcre
编译通过。

**Comment by jack338c** [comment]
@chuntsky 
it works 
thanks
