### ISSUE TITLE
libmbedcrypto.so.0 not found

### ISSUE THREAD

**Issue by mfat** [honwen/openwrt-shadowsocksr#6]
Hi 

Running on glinet Ar300m i get the following error:

Error loading shared library libmbedcrypto.so.0: No such file or directory (needed by /usr/bin/ssr-redir)
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_update: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_free: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_setkey: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_aes_setkey_enc: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_finish: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_hmac: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_reset: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_starts: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_update: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_set_iv: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_aes_crypt_cbc: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_get_size: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_init: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_setup: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_setup: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_info_from_type: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_free: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_cipher_info_from_string: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md_info_from_string: symbol not found
Error relocating /usr/bin/ssr-redir: mbedtls_md5: symbol not found

**Comment by honwen** [comment]
try build full rom instead of installing ipks
