### ISSUE TITLE
如何让ssr-redir将DNS请求转发到DNSCrypt-proxy并顺畅运行?

### ISSUE THREAD

**Issue by BlueHandsSpirits** [honwen/openwrt-shadowsocksr#7]
在固件版本19.07.0-rc2、内核版本4.14.156的openwrt上经过编译后成功安装openwrt-shadowsocksr与相应的luci-app-shadowsocksr，并按照 https://github.com/shadowsocksrr/shadowsocksr-libev/blob/Akkariiin/master/doc/ss-redir.asciidoc    范例中的指示运行了ssr-redir并添加了可用的服务器。

但当开启透明代理后不久ssr-redir自动停止，日志显示与dns有关，我想是ssr未能将dns请求转发到dnscrypt-proxy。

我根据 **https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-OpenWRT** 成功安装并设置了DNSCrypt-proxy到“127.0.0.5:53”(dnsmasq为127.0.0.1:53)，用了配备国内外ip分流规则的DoH服务器(ssr也将“中国ip网段”的txt文件加入被忽略IP列表了)。按理说能顺畅运行才对，我猜想本地解析并未完全转到dnsmasq再转到dnscrypt-proxy，想请求帮助。
（在ss-redir的iptables新链设定中，我把使用的ssr服务器统统加入了忽略的地址。但在dnscrypt-proxy相关的设定里我没有添加额外的忽略地址，不知是否与此有关？（请见上一段引用网址。）若有关，我是否应当添加ssr服务器以及其他一些地址？）

以上是正文，作为一个受惠于ss及ssr的普通用户，我非常感谢软件的各位创作者，鞠躬。

**Comment by honwen** [comment]
Try: https://github.com/honwen/openwrt-dnsmasq-extra

**Comment by BlueHandsSpirits** [comment]
你好，我将forwarder、dnscrypt、dnsmasq-extra编译后覆盖安装，没有其他更改。不再出现之前的错误，但还是有点小毛病：能上baidu、google，上不了yt、whoer.net，使用（网易的）dns检测有少数情况会出现本地运营商（以及德国纽伦堡美国之类）或者检测不出来的问题。我想让openwrt能分流国内外IP段并应用到所有设备上，但不知道怎么设置（只知道应该重新设置一下dnscrypt），请指教，以下是详情截图。
![微信截图_20191216154833](https://user-images.githubusercontent.com/58907334/70888957-760da400-201c-11ea-92c2-c967931c45ba.png)
![微信截图_20191216154847](https://user-images.githubusercontent.com/58907334/70888964-79a12b00-201c-11ea-92e4-2ba6ea8c12c6.png)

(或者有没有dnsmasq-extra说明文档之类的可以让我照着摸索摸索)

**Comment by honwen** [comment]
[dnscrypt.conf](https://github.com/honwen/openwrt-dnsmasq-extra/blob/master/dnscrypt/files/dnscrypt.conf#L4)
stop ssr, and use `dig @192.168.1.1 -p 7400` to check if dnscrypt works;
start ssr, and use `dig @192.168.1.1 -p 7400` to check if dnscrypt works;

**Comment by BlueHandsSpirits** [comment]
stop ssr
![dig3](https://user-images.githubusercontent.com/58907334/70905494-f93ff180-203e-11ea-9390-c3a77c0a1a00.png)

star ssr
![dig2](https://user-images.githubusercontent.com/58907334/70905502-fe04a580-203e-11ea-87db-ec7e6dc734bb.png)

经过对比，我发觉似乎是正常的。但是我测出来的DNS服务器经常在我自己使用的（geekdns）与其他一些DNS服务器之间转换，且经查询我发现后台同时运行着2个dnscrypt服务。
![未命名1576497875](https://user-images.githubusercontent.com/58907334/70905619-5045c680-203f-11ea-8841-f66f67828799.png)
我是否应该将先前运行的DNScrypt-proxy关掉？如果要关，那么我是否应该将新DNScrypt的地址改为先前设定的127.0.0.5:53以搭配之前的dnsmasq设置？(还是说此前的dnsmasq设置也变更了？)

：）

**Comment by honwen** [comment]
remove old `DNScrypt`: `/usr/sbin/dnscrypt-proxy`, and use `dnsmasq`;

let `dnsmasq-extra` handle it.

**Comment by BlueHandsSpirits** [comment]
:3
抱拳
